### ISSUE TITLE
usage for CrawlSpider

### ISSUE THREAD

**Issue by HenriPiot-dev** [patkle/scrapy-snippets#1]
Hello, I wonder if this method will work with a CrawlSpider and not a simple spider ?

**Comment by patkle** [comment]
Hello @HenriPiot-dev,

Since this is just a collection of snippets which I used to use for work, I have no clue which method you mean, please specify that. 
Actually probably none of the snippets will work out of the box without some modification, best case would be only adding a few settings to your settings.py file. 

Thanks,
Patrick

**Comment by patkle** [comment]
Closed this because there was no feedback on what the actual issue was.
